version: "3.8"

services:
  app:
    build: .
    container_name: ultra-docker-gui
    ports:
      - "5000:5000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # 👈 даём доступ к сокету Docker
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

  nginx:
    image: nginx:alpine
    container_name: ultra-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

